excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://umbrellat.github.io
title: Team Umbrellat
email: teamumbrellat@gmail.com
author: Team Umbrellat
description: My awesome new site
paginate: 3
google_analytics: 